### ISSUE TITLE
Import of large sets of images fails

### ISSUE THREAD

**Issue by nathanfranklin** [taggit-tacc/taggit#72]
### Bug

Fred:

> Tried to load 23 photos from /PRJ-2714/Data Sets by Location/Port of Ponce/Images by Structure/Warehouse A/Geotagged Images/ but only 8 photos loaded

Fred also shared 2 projects on DesignSafe with developers:
* PRJ-3468 -> https://www.designsafe-ci.org/data/browser/projects/6752662753351626260-242ac118-0001-012/  
* PRJ-2764 -> https://www.designsafe-ci.org/data/browser/projects/5737719449560355306-242ac116-0001-012/

### Screenshot

None

### Trace

Nathan testing importing all files from PRJ-3468 (https://www.designsafe-ci.org/data/browser/projects/6752662753351626260-242ac118-0001-012/   )

There is mostly this error:
```
 geoapiworkers | geoapi.utils.agave.AgaveFileGetError: Could not fetch file (project-6752662753351626260-242ac118-0001-012//Irma 2017/AHDE1093.jpg) status_code:500
````

but a few of the following which complain of missing EXIF data but at first glance looks like the file didn't get transferred properly:
```
geoapiworkers | [2022-05-06 19:13:53,219: ERROR/ForkPoolWorker-3] Task geoapi.tasks.external_data.import_file_from_agave[f185e2fa-222a-4167-8087-9547de95b375] raised unexpected: InvalidEXIFData()
geoapiworkers | Traceback (most recent call last):
geoapiworkers |   File "/app/geoapi/services/images.py", line 55, in processImage
geoapiworkers |     imdata = ImageService.resizeImage(fileObj)
geoapiworkers |   File "/app/geoapi/services/images.py", line 65, in resizeImage
geoapiworkers |     thumb = _fix_orientation(fileObj)
geoapiworkers |   File "/app/geoapi/services/images.py", line 82, in _fix_orientation
geoapiworkers |     im = Image.open(fileObj)
geoapiworkers |   File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 2896, in open
geoapiworkers |     "cannot identify image file %r" % (filename if filename else fp)
geoapiworkers | PIL.UnidentifiedImageError: cannot identify image file <tempfile._TemporaryFileWrapper object at 0x7f1b3deb6c10>
```

### Related issues

Jira:  https://jira.tacc.utexas.edu/browse/DES-2236

**Comment by nathanfranklin** [comment]
This is a issue mostly likely in TAPIS. I'm working through it and will pass this along to them.

**Comment by nathanfranklin** [comment]
This was fixed in https://github.com/TACC-Cloud/geoapi/pull/72
